src/Portfolio.WebMvc/Models/ErrorViewModel.cs
namespace Portfolio.WebMvc.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

src/Portfolio.WebMvc/Models/TransactionsListViewModel.cs
using Portfolio.Core.Models;

namespace Portfolio.WebMvc.Models
{
    public class TransactionsListViewModel
    {
        public List<Transaction>? Transactions { get; set; }
        public List<Asset>? Assets { get; set; }
        public TransactionFilter? Filter { get; set; }
    }
}

src/Portfolio.WebMvc/Controllers/AssetController.cs
using Microsoft.AspNetCore.Mvc;
using Portfolio.Core.Services;

namespace Portfolio.WebMvc.Controllers
{
    public class AssetController : Controller
    {
        private readonly IAssetsService _assetsService;

        public AssetController(IAssetsService assetsService)
        {
            _assetsService = assetsService;
        }

        public IActionResult Index()
        {
            return View();
        }

        public ViewResult List()
        {
            var assets = _assetsService.GetAssets();

            //var model = assets.Select(x => new Asset
            //{
            //    Id = x.Id,
            //    AssetGroupId = x.AssetGroupId,
            //    Code = x.Code,
            //    Name = x.Name
            //}).ToList();

            return View(assets);
        }
    }
}

src/Portfolio.WebMvc/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Portfolio.WebMvc.Models;

namespace Portfolio.WebMvc.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

src/Portfolio.WebMvc/Controllers/TransactionController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Portfolio.Core.Services;
using Portfolio.Core.Models;
using Portfolio.WebMvc.Models;
using Portfolio.Core.Extensions;

namespace Portfolio.WebMvc.Controllers
{
    public class TransactionController : Controller
    {
        private readonly ITransactionsService _transactionsService;
        private readonly IAssetsService _assetsService;

        public TransactionController(
            ITransactionsService transactionsService,
            IAssetsService assetsService)
        {
            _transactionsService = transactionsService;
            _assetsService = assetsService;
        }

        public IActionResult Index()
        {
            return View();
        }

        public ViewResult List(TransactionsListViewModel inputModel)
        {
            if (inputModel.Filter == null)
            {
                inputModel.Filter = new TransactionFilter
                {
                    DateFrom = DateTime.Today.GetStartOfTheYear()
                };
            }

            var transactions = _transactionsService.GetTransactions(inputModel.Filter);
            var assets = _assetsService.GetAssets();

            ViewBag.Assets = new SelectList(assets);

            var model = new TransactionsListViewModel
            {
                Transactions = transactions.ToList(),  
                Assets = assets.ToList(),
                Filter = inputModel.Filter
            };

            return View(model);
        }

        public ViewResult GetAssetsSummary()
        {
            var filter = new TransactionAggregateRequest
            {
                GroupByAsset = true
            };

            var data = _transactionsService.GetTransactionAggregate(filter);

            return View("AssetsSummary", data);
        }

        /// <summary>
        /// Sets some default values for filter in case it selects too much data.
        /// </summary>
        /// <param name="filter"></param>
        private void InitFilter(TransactionFilter filter)
        {
            if (filter != null)
            {
                return;
            }

            filter = new TransactionFilter
            {
                DateFrom = DateTime.Today.GetStartOfTheYear()
            };
        }
    }
}

src/Portfolio.WebMvc/Views/Asset/List.cshtml
@model IEnumerable<Portfolio.Core.Models.Asset>

@{
    ViewData["Title"] = "List";
}

<h1>List</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.AssetGroupId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.AssetGroupId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
            </td>
        </tr>
}
    </tbody>
</table>

src/Portfolio.WebMvc/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

src/Portfolio.WebMvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Portfolio</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Portfolio.WebMvc.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Portfolio</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Transaction" asp-action="GetAssetsSummary">Assets Summary</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Transaction" asp-action="List">Transactions</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Portfolio.WebMvc - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

src/Portfolio.WebMvc/Views/Transaction/AssetsSummary.cshtml
@model IEnumerable<Portfolio.Core.Models.TransactionAggregate>

@{
    ViewData["Title"] = "Asset Summary";
}

<h1>@ViewData["Title"]</h1>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.AssetName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ExpensesSum)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IncomeSum)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Balance)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.AssetName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ExpensesSum)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IncomeSum)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Balance)
            </td>
            <td>
                @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ })
            </td>
        </tr>
}
    </tbody>
</table>

src/Portfolio.WebMvc/Views/Transaction/List.cshtml
@model TransactionsListViewModel

@{
    ViewData["Title"] = "Transactions";
}

<h1>Transactions</h1>

@using (Html.BeginForm())
{
    <p>
        Asset: @Html.DropDownListFor(
            x => x.Filter.AssetId,
            new SelectList(
                Model.Assets,
                "Id",
                "Name"
            ),
            "Choose Asset"
        )
        <input type="submit" value="Filter"/>
    </p>
    <p>
        Date From: @Html.EditorFor(x => x.Filter.DateFrom, new { @Value = Model.Filter.DateFrom })
    </p>
    <p>
        Date To: @Html.EditorFor(x => x.Filter.DateTo)
    </p>
}

<table class="table">
    <thead>
        <tr>
@*             <th>
                Id
            </th> *@
            <th>
                AssetName
            </th>
            <th>
                TransactionTime
            </th>
            <th>
                TransactionType
            </th>
            <th>
                Volume
            </th>
            <th>
                PriceInCurrency
            </th>
            <th>
                Price
            </th>
            <th>
                Currency
            </th>
            <th>
                Commission
            </th>
            <th>
                Amount
            </th>
            <th>
                Balance
            </th>
@*             <th>
                Buy transactions
            </th> *@
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model.Transactions) {
        <tr>
@*             <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td> *@
            <td>
                @Html.DisplayFor(modelItem => item.AssetName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TransactionTime)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TransactionType)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Volume)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PriceInCurrency)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Currency)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Commission)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Amount)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Balance)
            </td>
@*             <td>
                @Html.DisplayFor(modelItem => item.BuyTransactionIds)
            </td> *@
        </tr>
}
    </tbody>
    <tfoot>
        <tr>
            <td colspan="9"></td>
            <td>
                @Math.Round(
                    Model.Transactions
                    .Where(
                        x => x.TransactionType == Portfolio.Core.Models.TransactionType.Sell)
                        .Sum(x => x.Balance),
                    2
                )
            </td>
        </tr>
    </tfoot>
</table>